export const AUTH_USER_LOGOUT_REQUEST = 'AUTH_USER_LOGOUT_REQUEST';
export const AUTH_USER_LOGOUT_SUCCESS = 'AUTH_USER_LOGOUT_SUCCESS';
export const AUTH_USER_LOGOUT_FAILURE = 'AUTH_USER_LOGOUT_FAILURE';
export const AUTH_USER_LOGIN_REQUEST  = 'AUTH_USER_LOGIN_REQUEST';
export const AUTH_USER_LOGIN_SUCCESS  = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_USER_LOGIN_FAILURE  = 'AUTH_USER_LOGIN_FAILURE';