export const MESSAGE_IN_CHANGE_PER_PAGE = 'BILL_MESSAGE_IN_CHANGE_PER_PAGE';
export const MESSAGE_IN_CHANGE_PAGE = 'BILL_MESSAGE_IN_CHANGE_PAGE';

export const MESSAGE_OUT_CHANGE_PER_PAGE = 'BILL_MESSAGE_OUT_CHANGE_PER_PAGE';
export const MESSAGE_OUT_CHANGE_PAGE = 'BILL_MESSAGE_OUT_CHANGE_PAGE';

export const REJECTED_IN_CHANGE_PER_PAGE = 'BILL_REJECTED_IN_CHANGE_PER_PAGE';
export const REJECTED_IN_CHANGE_PAGE = 'BILL_REJECTED_IN_CHANGE_PAGE';

export const REJECTED_OUT_CHANGE_PER_PAGE = 'BILL_REJECTED_OUT_CHANGE_PER_PAGE';
export const REJECTED_OUT_CHANGE_PAGE = 'BILL_REJECTED_OUT_CHANGE_PAGE';

export const RECONCILIATION_ACT_CHANGE_PER_PAGE = 'RECONCILIATION_ACT_CHANGE_PER_PAGE';
export const RECONCILIATION_ACT_CHANGE_PAGE = 'RECONCILIATION_ACT_CHANGE_PAGE';