export const BILL_FILTER_PERIOD_SET = 'BILL_FILTER_PERIOD_SET';
export const BILL_FILTER_ORGANIZATION_SET = 'BILL_FILTER_ORGANIZATION_SET';
export const BILL_FILTER_CATEGORY_SET = 'BILL_FILTER_CATEGORY_SET';
export const BILL_FILTER_DATE_FROM_SET = 'BILL_FILTER_DATE_FROM_SET';
export const BILL_FILTER_DATE_TO_SET = 'BILL_FILTER_DATE_TO_SET';
export const BILL_FILTER_STATUS_SET = 'BILL_FILTER_STATUS_SET';