export const MESSAGE_IN_GET_REQUEST = 'BILL_MESSAGE_IN_GET_REQUEST';
export const MESSAGE_IN_GET_SUCCESS = 'BILL_MESSAGE_IN_GET_SUCCESS';
export const MESSAGE_IN_GET_FAILURE = 'BILL_MESSAGE_IN_GET_FAILURE';

export const MESSAGE_OUT_GET_REQUEST = 'BILL_MESSAGE_OUT_GET_REQUEST';
export const MESSAGE_OUT_GET_SUCCESS = 'BILL_MESSAGE_OUT_GET_SUCCESS';
export const MESSAGE_OUT_GET_FAILURE = 'BILL_MESSAGE_OUT_GET_FAILURE';

export const REJECTED_IN_GET_REQUEST = 'BILL_REJECTED_IN_GET_REQUEST';
export const REJECTED_IN_GET_SUCCESS = 'BILL_REJECTED_IN_GET_SUCCESS';
export const REJECTED_IN_GET_FAILURE = 'BILL_REJECTED_IN_GET_FAILURE';

export const REJECTED_OUT_GET_REQUEST = 'BILL_REJECTED_OUT_GET_REQUEST';
export const REJECTED_OUT_GET_SUCCESS = 'BILL_REJECTED_OUT_GET_SUCCESS';
export const REJECTED_OUT_GET_FAILURE = 'BILL_REJECTED_OUT_GET_FAILURE';

export const RECONCILIATION_ACT_GET_REQUEST = 'RECONCILIATION_ACT_GET_REQUEST';
export const RECONCILIATION_ACT_GET_SUCCESS = 'RECONCILIATION_ACT_GET_SUCCESS';
export const RECONCILIATION_ACT_GET_FAILURE = 'RECONCILIATION_ACT_GET_FAILURE';