export const CADESPLUGIN_CHECK = 'CADESPLUGIN_CHECK';
export const CADESPLUGIN_AVAILABLE = 'CADESPLUGIN_AVAILABLE';
export const CADESPLUGIN_NOT_AVAILABLE = 'CADESPLUGIN_NOT_AVAILABLE';
export const CADES_CERT_GET_REQUEST = 'CADES_CERT_GET_REQUEST';
export const CADES_CERT_GET_SUCCESS = 'CADES_CERT_GET_SUCCESS';
export const CADES_CERT_GET_FAILURE = 'CADES_CERT_GET_FAILURE';

export const CADESCOM_CADES_BES = 1;
export const CAPICOM_CURRENT_USER_STORE = 2;
export const CAPICOM_MY_STORE = "My";
export const CAPICOM_STORE_OPEN_MAXIMUM_ALLOWED = 2;
export const CAPICOM_CERTIFICATE_FIND_SUBJECT_NAME = 1;
export const CADESCOM_BASE64_TO_BINARY = 1;
export const CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_256 = 101;