export const MESSAGE_IN_GET_REQUEST = 'DISPLIST_MESSAGE_IN_GET_REQUEST';
export const MESSAGE_IN_GET_SUCCESS = 'DISPLIST_MESSAGE_IN_GET_SUCCESS';
export const MESSAGE_IN_GET_FAILURE = 'DISPLIST_MESSAGE_IN_GET_FAILURE';
