export const MESSAGE_IN_GET_REQUEST = 'EXPERTISE_MESSAGE_IN_GET_REQUEST';
export const MESSAGE_IN_GET_SUCCESS = 'EXPERTISE_MESSAGE_IN_GET_SUCCESS';
export const MESSAGE_IN_GET_FAILURE = 'EXPERTISE_MESSAGE_IN_GET_FAILURE';
export const MESSAGE_OUT_GET_REQUEST = 'EXPERTISE_MESSAGE_OUT_GET_REQUEST';
export const MESSAGE_OUT_GET_SUCCESS = 'EXPERTISE_MESSAGE_OUT_GET_SUCCESS';
export const MESSAGE_OUT_GET_FAILURE = 'EXPERTISE_MESSAGE_OUT_GET_FAILURE';

export const MEE_MESSAGE_IN_GET_REQUEST = 'EXPERTISE_MEE_GET_REQUEST';
export const MEE_MESSAGE_IN_GET_SUCCESS = 'EXPERTISE_MEE_GET_SUCCESS';
export const MEE_MESSAGE_IN_GET_FAILURE = 'EXPERTISE_MEE_GET_FAILURE';