export const MESSAGE_IN_CHANGE_PER_PAGE = 'EXPERTISE_MESSAGE_IN_CHANGE_PER_PAGE';
export const MESSAGE_IN_CHANGE_PAGE = 'EXPERTISE_MESSAGE_IN_CHANGE_PAGE';
export const MESSAGE_OUT_CHANGE_PER_PAGE = 'EXPERTISE_MESSAGE_OUT_CHANGE_PER_PAGE';
export const MESSAGE_OUT_CHANGE_PAGE = 'EXPERTISE_MESSAGE_OUT_CHANGE_PAGE';

export const MEE_MESSAGE_IN_CHANGE_PER_PAGE = 'EXPERTISE_MEE_CHANGE_PER_PAGE';
export const MEE_MESSAGE_IN_CHANGE_PAGE = 'EXPERTISE_MEE_CHANGE_PAGE';