export const MEDICAL_INSTITUTION_GET_REQUEST = 'MEDICAL_INSTITUTION_GET_REQUEST';
export const MEDICAL_INSTITUTION_GET_SUCCESS = 'MEDICAL_INSTITUTION_GET_SUCCESS';
export const MEDICAL_INSTITUTION_GET_FAILURE = 'MEDICAL_INSTITUTION_GET_FAILURE';