export const MESSAGE_IN_CHANGE_PER_PAGE = 'MESSAGE_IN_CHANGE_PER_PAGE';
export const MESSAGE_IN_CHANGE_PAGE = 'MESSAGE_IN_CHANGE_PAGE';
export const MESSAGE_OUT_CHANGE_PER_PAGE = 'MESSAGE_OUT_CHANGE_PER_PAGE';
export const MESSAGE_OUT_CHANGE_PAGE = 'MESSAGE_OUT_CHANGE_PAGE';