export const MESSAGE_IN_GET_REQUEST = 'MESSAGE_IN_GET_REQUEST';
export const MESSAGE_IN_GET_SUCCESS = 'MESSAGE_IN_GET_SUCCESS';
export const MESSAGE_IN_GET_FAILURE = 'MESSAGE_IN_GET_FAILURE';
export const MESSAGE_OUT_GET_REQUEST = 'MESSAGE_OUT_GET_REQUEST';
export const MESSAGE_OUT_GET_SUCCESS = 'MESSAGE_OUT_GET_SUCCESS';
export const MESSAGE_OUT_GET_FAILURE = 'MESSAGE_OUT_GET_FAILURE';