export const MESSAGE_IN_GET_REQUEST = 'REGISTER_MESSAGE_IN_GET_REQUEST';
export const MESSAGE_IN_GET_SUCCESS = 'REGISTER_MESSAGE_IN_GET_SUCCESS';
export const MESSAGE_IN_GET_FAILURE = 'REGISTER_MESSAGE_IN_GET_FAILURE';

export const REJECTED_IN_GET_REQUEST = 'REGISTER_REJECTED_IN_GET_REQUEST';
export const REJECTED_IN_GET_SUCCESS = 'REGISTER_REJECTED_IN_GET_SUCCESS';
export const REJECTED_IN_GET_FAILURE = 'REGISTER_REJECTED_IN_GET_FAILURE';